# Generated by Django 5.0.4 on 2024-04-16 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_pessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereço', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('data_nacimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('profissão', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='exames_hemograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_glicemia', models.FloatField()),
                ('nivel_colesterol', models.FloatField()),
                ('nivel_plasmaticos_colesterol', models.FloatField()),
                ('nivel_trigicerideos', models.FloatField()),
                ('nivel_lipoproteinas_plasmaticos', models.FloatField()),
                ('nivel_pressão_aterial', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_1', models.BooleanField()),
                ('pergunta_2', models.BooleanField()),
                ('pergunta_3', models.BooleanField()),
                ('pergunta_4', models.BooleanField()),
                ('pergunta_5', models.BooleanField()),
                ('pergunta_6', models.BooleanField()),
                ('pergunta_7', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='exames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doenças_familiares', models.TextField()),
                ('doenças_pessoas', models.TextField()),
                ('doenças_atual', models.TextField()),
                ('remedios', models.TextField()),
                ('fuma', models.BooleanField()),
                ('consumo_alcool', models.BooleanField()),
                ('tempo_medio_sono', models.IntegerField()),
                ('exame_sanque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anamnese.exames_hemograma')),
            ],
        ),
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dados_pessoais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anamnese.dados_pessoais')),
                ('exames', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anamnese.exames')),
                ('questionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anamnese.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.TextField()),
                ('CPF', models.CharField(max_length=25)),
                ('ficha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anamnese.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medico', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.TextField()),
                ('CPF', models.CharField(max_length=25)),
                ('CRM', models.CharField(max_length=100)),
                ('ficha', models.ManyToManyField(to='anamnese.ficha')),
            ],
        ),
    ]
