# Generated by Django 5.0.4 on 2024-04-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dados_pessoais',
            new_name='Dado_pessoal',
        ),
        migrations.RenameModel(
            old_name='exames',
            new_name='exame',
        ),
        migrations.RenameModel(
            old_name='exames_hemograma',
            new_name='exame_hemograma',
        ),
    ]
