# Generated by Django 5.0.4 on 2024-04-26 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0003_rename_data_nacimento_dado_pessoal_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dado_pessoal',
            old_name='data_nascimento',
            new_name='data_nacimento',
        ),
        migrations.RenameField(
            model_name='exame',
            old_name='doencas_atual',
            new_name='doenças_atual',
        ),
        migrations.RenameField(
            model_name='exame',
            old_name='doencas_familiares',
            new_name='doenças_familiares',
        ),
        migrations.RenameField(
            model_name='exame',
            old_name='doencas_pessoais',
            new_name='doenças_pessoas',
        ),
        migrations.RenameField(
            model_name='exame',
            old_name='exame_sangue',
            new_name='exame_sanque',
        ),
        migrations.RenameField(
            model_name='exame_hemograma',
            old_name='nivel_pressao_arterial',
            new_name='nivel_pressão_aterial',
        ),
        migrations.RenameField(
            model_name='exame_hemograma',
            old_name='nivel_triglicerideos',
            new_name='nivel_trigicerideos',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='dados_pessoais',
            new_name='Dados_pessoais',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='fichas',
            new_name='ficha',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='ficha',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='anamnese.ficha'),
        ),
    ]
