# Generated by Django 5.0.4 on 2024-04-27 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0004_rename_data_nascimento_dado_pessoal_data_nacimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado_pessoal',
            name='data_nacimento',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='exame_sanque',
        ),
        migrations.RemoveField(
            model_name='exame_hemograma',
            name='nivel_pressão_aterial',
        ),
        migrations.RemoveField(
            model_name='exame_hemograma',
            name='nivel_trigicerideos',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='Dados_pessoais',
        ),
        migrations.AddField(
            model_name='dado_pessoal',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exame',
            name='exame_sangue',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='anamnese.exame_hemograma'),
        ),
        migrations.AddField(
            model_name='exame_hemograma',
            name='nivel_pressão_arterial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exame_hemograma',
            name='nivel_triglicerideos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='CPF',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_usuario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dado_pessoal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='dado_pessoal',
            name='endereço',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dado_pessoal',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dado_pessoal',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dado_pessoal',
            name='profissão',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dado_pessoal',
            name='sexo',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='exame',
            name='consumo_alcool',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='doenças_atual',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='doenças_familiares',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='doenças_pessoas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='fuma',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='remedios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exame',
            name='tempo_medio_sono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exame_hemograma',
            name='nivel_colesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exame_hemograma',
            name='nivel_glicemia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exame_hemograma',
            name='nivel_lipoproteinas_plasmaticos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exame_hemograma',
            name='nivel_plasmaticos_colesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='exames',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='anamnese.exame'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='questionario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='anamnese.questionario'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_1',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_2',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_3',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_4',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_5',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_6',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='pergunta_7',
            field=models.BooleanField(blank=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='dados_pessoais',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='anamnese.dado_pessoal'),
        ),
    ]
