# Generated by Django 5.1.3 on 2024-11-11 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0005_remove_dado_pessoal_data_nacimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='dados_pessoais',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='exame_sangue',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='exames',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='questionario',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='ficha',
        ),
        migrations.AddField(
            model_name='ficha',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='doencas_atual',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='doencas_familiares',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='doencas_pessoais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='endereco',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nivel_colesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nivel_glicemia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nivel_lipoproteinas_plasmaticos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nivel_plasmaticos_colesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nivel_pressão_arterial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nivel_triglicerideos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='remedios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sexo',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tempo_medio_sono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anamnese.cadastro'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Dado_pessoal',
        ),
        migrations.DeleteModel(
            name='exame_hemograma',
        ),
        migrations.DeleteModel(
            name='exame',
        ),
        migrations.DeleteModel(
            name='medico',
        ),
        migrations.DeleteModel(
            name='questionario',
        ),
    ]
