# Generated by Django 5.1.4 on 2025-01-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnese', '0006_remove_ficha_dados_pessoais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='alcool',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ficha',
            name='fuma',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sexo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
